### PR TITLE
[T3A4][F10-A1]Joel Foo

### PR DESCRIPTION
**Pull request by jaeoheeail**
Ready for review.

Some code adapted from #71 (I followed the same technique to check if storage file exists)

### CODE REVIEW

**Comment by Candiie** [comment]
Since we've discussed it in detailed during the tutorial ~ this was marked as accepted w/o review :)

**Comment by Candiie** [comment]
Hi Joel, btw my sincere apologies for the confusion once again during the tutorial as I've misunderstood your explanation previously. Hope that the subsequent explanation have resolve any misunderstanding, however, don't hesitate if you have further questions.

**Comment by jaeoheeail** [comment]
Just to clarify,

Both implementations are correct, however mine is only correct if we exit upon saving and only if our intention is not to recover the file right? If i remembered correctly, you mentioned that the preferred (especially for User Experience) should be to put it in the save method and let it recover?

**Comment by Candiie** [comment]
Hi , 

Yupp, actually the correctness is debatable, it really depends because many different people interpret it a different way, so there is no correct or wrong. However as elaborated during the tutorial and as you mention, UX is also an extremely important aspect in SE, so to me personally, considering the point as a user, I would prefer the program to pop a msg and show some form of warning and continue letting the program run instead of my program crashing without auto-saving my file :) 

So if were to ask how would you go about improving the UX, this is a possible way: detect the file deletion at the beginning of the "StorageFile::store()" method but throw the exception at the end of the method, follow by catching in "Main::executeCommand()" and show a warning to the user instead of terminating program would be a better form of excecution. 

Hope my explanation have better clarified any of your doubts :)

**Comment by Candiie** [comment]
Some comments added. Please close the PR after reading comments

**Comment by jaeoheeail** [comment]
Thanks for the explanation on the entire process!

**Pull request closed without merging**
