### PR TITLE
[T3A3][W13-A3] Mok Wei Xiong, Edmund

### PR DESCRIPTION
**Pull request by edmundmok**

### CODE REVIEW

**Comment by edmundmok** [comment]
Branched from T3A2, so T3A3 starts from commit fc36dea and ends at 9ff9b31.

**Comment by edmundmok** [comment]
Branched from T3A2, so T3A3 starts from commit fc36dea and ends at b75be8b.

**Comment by michelletan** [comment]
Hey Edmund, please split up your activities into separate PRs. I couldn't find a PR for T3A2. 

Good work for T3A3 though! I see that you remembered to update the tests. Do take note of the indentation for your header comments, it's off by a few spaces.

**Comment by edmundmok** [comment]
I think you closed the T3A2 a few days ago already!

**Pull request closed without merging**
