### PR TITLE
[T3A4][W09-A3]Xiao Pu

### PR DESCRIPTION
**Pull request by xpdavid**

### CODE REVIEW

**Comment by xpdavid** [comment]
Ready for review

**Comment by xpdavid** [comment]
Ready for review

**Comment by ashley-si** [comment]
Your code interrupts the program if the file is deleted. While your way of handling is definitely accepted, you may also consider showing an error message and re-create the file for the user

**Comment by ashley-si** [comment]
@xpdavid Some comments added. Please close the PR after reading comments

**Pull request closed without merging**
